version: '3'
services:
  backend:
    container_name: flask.aggr
    build:
      context: .
      dockerfile: Dockerfile_flask
    restart: always
    depends_on:
      - db

  web:
    container_name: nginx.aggr
    build:
      context: Dockerfile_nginx/.
      dockerfile: Dockerfile_nginx
    ports:
    - "81:80"
    restart: always

  db:
    image: postgres
    restart: always
    container_name: postgres.aggr
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432